version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.15

aliases:
  - &docker-image
    docker:
      - image: circleci/node:10

  - &install_aws_cli aws-cli/install

  - &install_typescript_globally
    run:
      name: Install Typescript globally
      command: yarn global add typescript

  - &configure_aws_cli
    aws-cli/configure:
      aws-region: 'AWS_REGION'
      aws-access-key-id: 'AWS_ACCESS_KEY_ID'
      aws-secret-access-key: 'AWS_SECRET_ACCESS_KEY'

  - &deploy
    run:
      name: Deploy
      command: yarn deploy

  - &deploy_production_filters
    filters:
      branches:
        only: master

  - &restore-build-flag
      restore_cache:
        keys:
          - build-flag-{{ checksum "package.json" }}

  - &test-build-flag
      run:
        name: Exit if build flag exists
        command: |
          FILE=build.flag
          if test -f "$FILE"; then
              echo "$FILE exist"
              circleci step halt
          fi

  - &generate-lock-file
      run:
        name: Generate lock file
        command: yarn generate-lock-entry >> yarn.lock

  - &restore-cache
      restore_cache:
        keys:
          - dependencies-cache-{{ checksum "yarn.lock" }}

  - &save-cache
      save_cache:
        paths:
          - node_modules
        key: dependencies-cache-{{ checksum "yarn.lock" }}

commands:
  save-build-flag:
    steps:
      - run:
          name: Create build flag
          command: touch build.flag
      - save_cache:
          paths:
            - build.flag
          key:
            build-flag-{{ checksum "package.json" }}

  node-build-steps:
    steps:
      - checkout:
          # Since our working_directory is deeper than the root,
          # remind the job where it needs to checkout.
          path: ~/yarn-circleci-monorepo
      - *restore-build-flag
      - *test-build-flag
      # Services and packages in a Workspace don't get their own
      # yarn.lock so we need to generate them manually.
      - *generate-lock-file
      - *restore-cache
      - *install_aws_cli
      - *configure_aws_cli
      - run:
          name: Build
          command: |
            yarn
            yarn build
            rm -rf src
      - *save-cache
      - run:
          name: Prune
          command: |
            yarn --production
            yarn package
      - run:
          name: Deploy
          command: yarn deploy
      - save-build-flag

jobs:
  build-service-a:
    docker:
      - image: circleci/node:10

    # This makes all commands from here on out relative to service-a
    working_directory: ~/yarn-cicleci-monorepo/services/service-a

    steps:
      - node-build-steps

workflows:
  version: 2
  service-a:
    jobs:
      - build-service-a:
          <<: *deploy_production_filters
          context: aws-production

